### ISSUE TITLE
charmap codec cant decode byte 0x90..

### ISSUE THREAD

**Issue by jstodda** [fdalvi/groupme-archiver#1]
Believe there is a unicode issue when rendering the thread from the JSON format to HTML (attempted).
Using Python 3 vs 2 (apparently introduced the issue)

The download worked perfectly but getting this error after the render to HTML attempt.

C:\Users\stars\Python\Groupme>python render_chat.py -i TheFam
Traceback (most recent call last):
  File "render_chat.py", line 371, in <module>
    main()
  File "render_chat.py", line 313, in main
    messages = json.load(fp)
  File "C:\Users\stars\AppData\Local\Programs\Python\Python38-32\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "C:\Users\stars\AppData\Local\Programs\Python\Python38-32\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 42250: character maps to <undefined>

Open to an edit that would encode to UTF or other format to avoid the error. Thanks!

**Comment by rarmocida** [comment]
I am a total noob to coding, but I was finally able to work my way through all of it and then I also got this error. At least I know I'm doing something right I guess. Is there any way to get it to render as I really like how it looked as you showed in screenshots?
